/*
 * RegisterFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.view;

import java.awt.Font;
import java.sql.Connection;

import javax.swing.JOptionPane;

import com.dao.UserDao;
import com.dao.impl.UserDaoImpl;
import com.model.User;
import com.util.DbUtil;
import com.util.StringUtil;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.ImageIcon;

/**
 *
 * @author __USER__
 */
public class User_RegisterFrm extends javax.swing.JFrame
{
	DbUtil dbUtil = new DbUtil();
	UserDao userDao = new UserDaoImpl();

	/** Creates new form RegisterFrm */
	public User_RegisterFrm()
	{
		Font font = new Font("Dialog", Font.PLAIN, 12);
		java.util.Enumeration keys = UIManager.getDefaults().keys();
		while (keys.hasMoreElements())
		{
			Object key = keys.nextElement();
			Object value = UIManager.get(key);
			if (value instanceof javax.swing.plaf.FontUIResource)
			{
				UIManager.put(key, font);
			}
		}
		initComponents();
		// 设置frame居中显示
		this.setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents()
	{

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jb_register = new javax.swing.JButton();
		jb_reset = new javax.swing.JButton();
		userNameTxt = new javax.swing.JTextField();
		emailTxt = new javax.swing.JTextField();
		passwordTxt = new javax.swing.JPasswordField();
		passwordConfirmTxt = new javax.swing.JPasswordField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u65b0\u7528\u6237\u6ce8\u518c");

		jLabel1.setFont(new java.awt.Font("宋体", 1, 18));
		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new_register.png"))); // NOI18N
		jLabel1.setText("\u65b0\u7528\u6237\u6ce8\u518c");

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new_user.png"))); // NOI18N
		jLabel2.setText("\u7528\u6237\u540d\uff1a");

		jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new_password.png"))); // NOI18N
		jLabel3.setText("\u5bc6\u7801\uff1a");

		jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password_config.png"))); // NOI18N
		jLabel4.setText("\u786e\u8ba4\u5bc6\u7801\uff1a");

		jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/email.png"))); // NOI18N
		jLabel5.setText("\u90ae\u7bb1\uff1a");

		jb_register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register.png"))); // NOI18N
		jb_register.setText("\u6ce8\u518c");
		jb_register.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				jb_registerActionPerformed(evt);
			}
		});

		jb_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset.png"))); // NOI18N
		jb_reset.setText("\u91cd\u7f6e");
		jb_reset.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				jb_resetActionPerformed(evt);
			}
		});
		
		JLabel label = new JLabel();
		label.setIcon(new ImageIcon(User_RegisterFrm.class.getResource("/images/search1.png")));
		label.setText("\u4F59\u989D\uFF1A");
		
		money = new JTextField();
		
		label_1 = new JLabel();
		label_1.setIcon(new ImageIcon(User_RegisterFrm.class.getResource("/images/bookTypeManager.png")));
		label_1.setText("\u662F\u5426\u4E3A\u6CE8\u518C\u7528\u6237\uFF1A");
		
		register1 = new JTextField();

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGap(95)
					.addComponent(jLabel1)
					.addContainerGap())
				.addGroup(layout.createSequentialGroup()
					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
						.addGroup(layout.createSequentialGroup()
							.addGap(40)
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addComponent(label_1)
								.addComponent(jLabel2)
								.addComponent(jLabel5)
								.addComponent(jLabel3)
								.addComponent(jLabel4)
								.addComponent(label, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(ComponentPlacement.RELATED))
						.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
							.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(jb_register)
							.addGap(18)))
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addComponent(money, GroupLayout.PREFERRED_SIZE, 146, GroupLayout.PREFERRED_SIZE)
								.addGroup(layout.createParallelGroup(Alignment.TRAILING)
									.addComponent(passwordConfirmTxt, GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
									.addComponent(emailTxt, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
									.addComponent(userNameTxt, GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
									.addComponent(passwordTxt, GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
								.addComponent(register1, GroupLayout.PREFERRED_SIZE, 146, GroupLayout.PREFERRED_SIZE))
							.addGap(40))
						.addGroup(layout.createSequentialGroup()
							.addGap(32)
							.addComponent(jb_reset)
							.addContainerGap())))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGap(19)
					.addComponent(jLabel1)
					.addGap(18)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel2)
						.addComponent(userNameTxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel3)
						.addComponent(passwordTxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel4)
						.addComponent(passwordConfirmTxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(emailTxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel5))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(label)
						.addComponent(money, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(label_1)
						.addComponent(register1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addGap(15)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jb_reset)
						.addComponent(jb_register))
					.addContainerGap())
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>
		// GEN-END:initComponents
		// 注册验证操作

	private void jb_registerActionPerformed(java.awt.event.ActionEvent evt)
	{
		String userName = this.userNameTxt.getText();
		String password = new String(this.passwordTxt.getPassword());
		String passwordConfirm = new String(this.passwordConfirmTxt.getPassword());
		String email = this.emailTxt.getText();
		String money1 = this.money.getText();
		float money = Float.parseFloat(money1);
		String register2 = register1.getText();
		boolean register = Boolean.parseBoolean(register2);
		
		if (StringUtil.isEmpty(userName))
		{
			JOptionPane.showMessageDialog(null, "用户名不能为空");
			return;
		}
		if (StringUtil.isEmpty(password))
		{
			JOptionPane.showMessageDialog(null, "密码不能为空");
			return;
		}
		if (!password.equals(passwordConfirm))
		{
			JOptionPane.showMessageDialog(null, "两次输入的密码不一致！");
			return;
		}
		if (!StringUtil.checkEmail(email))
		{
			JOptionPane.showMessageDialog(null, "邮箱格式错误！");
			return;
		}
		User user = new User(userName, password, email, money, register);
		Connection con = null;
		try
		{
			con = dbUtil.getCon();
			if (!userDao.isUserExist(con, user))
			{
				int addNum = userDao.userAdd(con, user);
				if (addNum == 1)
				{
					JOptionPane.showMessageDialog(null, "注册成功！");
					this.dispose();
					new LogOnFrm().setVisible(true);
				} else
				{
					JOptionPane.showMessageDialog(null, "注册失败");
				}
			} else
			{
				JOptionPane.showMessageDialog(null, "用户名存在，请重新输入！");
			}
		} catch (Exception e)
		{
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, "注册失败，请重新注册！");
		} finally
		{
			try
			{
				dbUtil.closeCon(con);
			} catch (Exception e)
			{
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

	}

	// 重置表单
	private void jb_resetActionPerformed(java.awt.event.ActionEvent evt)
	{
		this.userNameTxt.setText("");
		this.passwordTxt.setText("");
		this.passwordConfirmTxt.setText("");
		this.emailTxt.setText("");
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[])
	{
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run()
			{
				new User_RegisterFrm().setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextField emailTxt;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JButton jb_register;
	private javax.swing.JButton jb_reset;
	private javax.swing.JPasswordField passwordConfirmTxt;
	private javax.swing.JPasswordField passwordTxt;
	private javax.swing.JTextField userNameTxt;
	private JTextField money;
	private JLabel label_1;
	private JTextField register1;
}